### ISSUE TITLE
Nodes does not have the same interface name

### ISSUE THREAD

**Issue by emerout** [immanuelfodor/kube-karp#5]
I have several nodes (various hardware), which have different interface names:
`enp4s0`, `enp0s10`, `enp3s0`

How can I configure each node with a different iface ?

**Comment by emerout** [comment]
As a workaround,  I have renamed the interfaces for each node in `/etc/netplan/01-netcfg.yaml`:

```
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      match:
        macaddress: "c0:3f:00:01:02:03"
      set-name: eth0
      dhcp4: no
      addresses: [192.168.1.13/24]
      gateway4: 192.168.1.1
      nameservers:
        addresses: [192.168.1.1]
```
